### ISSUE TITLE
Autocalc md5 if not provided

### ISSUE THREAD

**Issue by steveoc64** [freman/gmrisa#1]
If you leave out the image_md5 from the payload, returns a 500.  Dont know if that could be a bit friendlier maybe.

Could auto-generate the image_md5 if its missing from the payload (ie - fetch the image and compute the md5 ?) if its really needed that is.

This is cool - already ran it over a number of original photos I have here, and found re-usage of the same image on the interwebz.  Pretty awesome :)

**Comment by freman** [comment]
I'd rather not waste the bandwidth downloading the original image.

It is basically just converting google reverse image search into an api so you can always just run your images there.

I use javascript in a browser page to md5 the image before calling this

**Comment by steveoc64** [comment]
fair call, does add a whack of bandwidth for a requirement that is higher up the food chain.

Im thinking of the use case where you have an img library on your server, and you want to periodically reverse image lookup all the images for copyright violations or whatever.   That logic belongs up in the app layer.
